[project]
name = "llama-guard"
version = "0.1.0"
description = "CVE database downloader and vectorized database for RAG"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
    "numpy>=1.24.0",
    "faiss-cpu>=1.7.4",
    "sentence-transformers>=2.2.0",
]
